### PR TITLE
Update go to 1.15 and change import paths

### PR DESCRIPTION
**Pull request by saschagrunert**
We should stick to the official sigs.k8s.io import paths as well as
use go 1.15. The dependencies go a bump to its latest version, too.

Documentation has been changed as needed.

### CODE REVIEW

**Comment by saschagrunert** [comment]
> @saschagrunert -- Can we bump this to go1.15 instead? It's right around the corner and k/k already uses it, albeit a pre-release version.

Sure
/hold 
for go 1.15

**Comment by justaugustus** [comment]
@saschagrunert -- should be okay to update this one now

**Comment by saschagrunert** [comment]
Updated the PR for go 1.15

**Pull request merged**
