### PR TITLE
Add release job and configurations and general housekeeping 

### PR DESCRIPTION
**Pull request by cpanato**
- upgrade to go1.22
- add version flag option
- add dependabot config
- add release job and configs

/hold

### CODE REVIEW

**Comment by cpanato** [comment]
need to update the test-infra jobs

**Comment by saschagrunert** [comment]
Let's cut a new release when everything is green and this one got merged.

**Comment by cpanato** [comment]
looks like the action did not kick, i will open a follow pr to check it

**Comment by cpanato** [comment]
> Let's cut a new release when everything is green and this one got merged.

let me run a follow up test before we cut it

**Pull request merged**
